[package]
name = "example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
client = { path = "../client" }

log = "0.4.14"
simple_logger = "1.16.0"

winapi = { version = "0.3.9", features = ["winnt", "libloaderapi", "winuser"] }