[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
pelite = "0.9.0"

thiserror = "1.0.30"

winapi = { version = "0.3.9", features = ["libloaderapi", "ioapiset"] }